name: Fetch Esports Data

on:
  schedule:
    - cron: '0 0 * * *' # Exécute chaque jour à minuit
  workflow_dispatch:

jobs:
  fetch-esports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch esports data
        run: |
          # Télécharger le fichier JSON depuis GitHub
          wget https://raw.githubusercontent.com/tiggy1er/apkgames/main/esports.json -O esports.json

          # Générer le contenu du fichier Lua
          echo 'local composer = require("composer")' > esports.lua
          echo 'local widget = require("widget")' >> esports.lua
          echo 'local json = require("json")' >> esports.lua
          echo 'local network = require("network")' >> esports.lua
          echo 'local theme = require("theme.colors")' >> esports.lua
          echo 'local native = require("native")' >> esports.lua
          echo 'local COLORS = require("theme.colors")' >> esports.lua
          echo '-- Add required Corona SDK globals' >> esports.lua
          echo 'local display = require("display")' >> esports.lua
          echo 'local system = require("system")' >> esports.lua
          echo 'local timer = require("timer")' >> esports.lua
          echo 'local SPORTS_GAMES = ' >> esports.lua
          cat esports.json | jq -c . >> esports.lua
          echo 'return SPORTS_GAMES' >> esports.lua

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add esports.lua
          git commit -m "Update esports.lua"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
